version: "3.1"
services:
  mc1:
    image: nextgenhealthcare/connect:3.8
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - SESSION_STORE=true
      - VMOPTIONS=-Xmx512m
    volumes:
      - ~/Documents/connect-docker/appdata1:/opt/connect/appdata
      - ~/Documents/connect-docker/custom_extensions:/opt/connect/custom-extensions
    secrets:
      - mirth_properties
      - mcserver_vmoptions
    expose:
      - 8080
      - 8443
    ports:
      - 8441:8443/tcp
    depends_on:
      - db
  mc2:
    image: nextgenhealthcare/connect:3.8
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - SESSION_STORE=true
      - DELAY=10
      - VMOPTIONS=-Xmx512m
    volumes:
      - ~/Documents/connect-docker/appdata2:/opt/connect/appdata
      - ~/Documents/connect-docker/custom_extensions:/opt/connect/custom-extensions
    secrets:
      - mirth_properties
      - mcserver_vmoptions
    expose:
      - 8080
      - 8443
    ports:
      - 8442:8443/tcp
    depends_on:
      - db
  haproxy:
    image: haproxy
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 9500:9500/tcp
    volumes:
      - ~/Documents/connect-docker/haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - mc1
      - mc2
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432

secrets:
  mirth_properties:
    file: ~/Documents/connect-docker/secret.properties
  mcserver_vmoptions:
    file: ~/Documents/connect-docker/secret.vmoptions
