version: "3.1"
services:
  mc:
    image: nextgenhealthcare/connect:3.8
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthdb
      - DATABASE_PASSWORD=mirthdb
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
    volumes:
      - ~/Documents/connect-docker/appdata:/opt/connect/appdata
      - ~/Documents/connect-docker/custom_extensions:/opt/connect/custom-extensions
    secrets:
      - mirth_properties
      - mcserver_vmoptions
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_PASSWORD=mirthdb
      - POSTGRES_DB=mirthdb
    expose:
      - 5432

secrets:
  mirth_properties:
    file: ~/Documents/connect-docker/secret.properties
  mcserver_vmoptions:
    file: ~/Documents/connect-docker/secret.vmoptions
